language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  
  - docker-compose -f docker-compose-build.yaml build --parallel

  - docker tag udagram-api-feed youssefmohsen/udagram-api-feed
  - docker tag reverseproxy youssefmohsen/reverseproxy
  - docker tag udagram-api-user youssefmohsen/udagram-api-user
  - docker tag udagram-frontend youssefmohsen/udagram-frontend

  

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push youssefmohsen/udagram-api-feed
  - docker push youssefmohsen/reverseproxy
  - docker push youssefmohsen/udagram-api-user
  - docker push youssefmohsen/udagram-frontend
